//
//  AppealService.swift
//  AppBlocker
//
//  Appeals against moderation results (rejected/flagged).
//  Supabase user_appeals table + file_appeal RPC (requires 039_moderation_notifications_appeals.sql).
//  Creation is only through the file_appeal RPC (no direct INSERT). Resolution (approve/reject) is
//  done by operators with a manual UPDATE in the SQL Editor (same as user_reports). On approval, the
//  resolve_user_appeal trigger sets the target's moderation_status back to 'approved' (the client does
//  not need to do anything).
//

import Foundation
import Supabase

/// Target of an appeal (post or comment). Same style as ReportSheetView.Target
enum AppealTarget: Identifiable, Hashable {
    case post(UUID)
    case comment(UUID)

    var id: String {
        switch self {
        case .post(let id):    return "post-\(id.uuidString)"
        case .comment(let id): return "comment-\(id.uuidString)"
        }
    }
}

/// 1 row of user_appeals (return value of fetchAppeal)
struct AppealRecord: Decodable {
    let id: UUID
    /// "pending" / "approved" / "rejected"
    let status: String
    let reason: String
    let resolutionNote: String?
    let createdAt: Date?

    enum CodingKeys: String, CodingKey {
        case id
        case status
        case reason
        case resolutionNote = "resolution_note"
        case createdAt      = "created_at"
    }
}

@MainActor
final class AppealService {

    static let shared = AppealService()

    private let client: SupabaseClient

    private init(client: SupabaseClient = SupabaseManager.shared.client) {
        self.client = client
    }

    /// Fetch the existing appeal for the target (nil if none). With RLS (user_appeals_select_own) only rows
    /// where auth.uid() = user_id are returned, so you can only see your own appeals.
    /// single() gives a PostgrestError on 0 rows, so it is not used; expressed with limit(1) + the first
    /// element of the array (user_appeals_unique_post / user_appeals_unique_comment allow at most 1 row per
    /// target)
    func fetchAppeal(for target: AppealTarget) async -> AppealRecord? {
        do {
            var query = client.from("user_appeals").select()
            switch target {
            case .post(let postId):
                query = query.eq("target_post_id", value: postId.uuidString)
            case .comment(let commentId):
                query = query.eq("target_comment_id", value: commentId.uuidString)
            }
            let records: [AppealRecord] = try await query
                .limit(1)
                .execute()
                .value
            return records.first
        } catch {
            print("⚠️ fetchAppeal failed for \(target): \(error)")
            return nil
        }
    }

    /// Among the given posts, return the set of post ids that have an appeal under review (pending).
    /// A bulk fetch to switch the pill on the restriction overlay to "異議申し立て中" ("Appeal pending")
    /// (2026-07-23 real device feedback: you cannot tell on the feed whether you already appealed).
    /// RLS (user_appeals_select_own) returns only your own appeal rows.
    /// For approved, the resolve trigger sets the post itself back to approved and the whole overlay
    /// disappears, so only pending needs to be picked up (rejected appeals keep the normal label)
    func fetchPendingAppealPostIds(for postIds: Set<UUID>) async -> Set<UUID> {
        guard !postIds.isEmpty else { return [] }
        struct Row: Decodable {
            let targetPostId: UUID?
            enum CodingKeys: String, CodingKey {
                case targetPostId = "target_post_id"
            }
        }
        do {
            let rows: [Row] = try await client
                .from("user_appeals")
                .select("target_post_id")
                .in("target_post_id", values: postIds.map(\.uuidString))
                .eq("status", value: "pending")
                .execute()
                .value
            return Set(rows.compactMap(\.targetPostId))
        } catch {
            print("⚠️ fetchPendingAppealPostIds failed: \(error)")
            return []
        }
    }

    // MARK: - Fetching the reason for the ruling (2026-07-22 real device feedback: "I want to see the full
    // reason why it's not OK")

    /// The target's current moderation ruling (status + AI reason text).
    /// The reason text is safety_reason (layer 1 rejected) / ethos_reason (layer 2 flagged) in the
    /// moderation_verdict jsonb, generated by the moderate-post Edge Function in the same Claude call as
    /// the ruling (no extra cost). RLS: the owner can SELECT their own post/comment rows, so use this only
    /// for display to the owner
    struct ModerationInfo {
        let status: String?
        let reason: String?
    }

    func fetchModerationInfo(for target: AppealTarget) async -> ModerationInfo? {
        struct VerdictRow: Decodable {
            let safetyReason: String?
            let ethosReason: String?
            enum CodingKeys: String, CodingKey {
                case safetyReason = "safety_reason"
                case ethosReason  = "ethos_reason"
            }
        }
        struct Row: Decodable {
            let moderationStatus: String?
            let moderationVerdict: VerdictRow?
            enum CodingKeys: String, CodingKey {
                case moderationStatus = "moderation_status"
                case moderationVerdict = "moderation_verdict"
            }
        }

        let table: String
        let id: UUID
        switch target {
        case .post(let postId):       table = "user_posts";    id = postId
        case .comment(let commentId): table = "user_comments"; id = commentId
        }

        do {
            let rows: [Row] = try await client
                .from(table)
                .select("moderation_status, moderation_verdict")
                .eq("id", value: id.uuidString)
                .limit(1)
                .execute()
                .value
            guard let row = rows.first else { return nil }
            // rejected prefers the layer 1 reason, flagged prefers the layer 2 reason (falls back to the other if
            // missing)
            let reason: String?
            switch row.moderationStatus {
            case "rejected": reason = row.moderationVerdict?.safetyReason ?? row.moderationVerdict?.ethosReason
            case "flagged":  reason = row.moderationVerdict?.ethosReason ?? row.moderationVerdict?.safetyReason
            default:         reason = nil
            }
            return ModerationInfo(status: row.moderationStatus, reason: reason)
        } catch {
            print("⚠️ fetchModerationInfo failed for \(target): \(error)")
            return nil
        }
    }

    enum FileResult {
        case filed
        case alreadyFiled
        case failed
    }

    /// Submit an appeal (file_appeal RPC). Only once per target (from the 2nd time on, .alreadyFiled).
    /// The RPC (SECURITY DEFINER) checks ownership (auth.uid() = owner of the post/comment) and
    /// moderation_status ('rejected'/'flagged' only) before the INSERT
    func fileAppeal(target: AppealTarget, reason: String) async -> FileResult {
        guard UserAuthService.shared.userId != nil else {
            print("⚠️ fileAppeal ignored: not signed in")
            return .failed
        }
        let trimmed = reason.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return .failed }

        // file_appeal(p_target_post_id, p_target_comment_id, p_reason) are all required arguments without a
        // DEFAULT (see 039 SQL). If the key for the non-target side is omitted, PostgREST returns a
        // missing-argument error, so always send both keys and send an explicit null with AnyJSON.null for the
        // non-target side (same pattern as UserAuthService.updateBio etc.: "avoid an Encodable struct omitting
        // nil keys")
        let postParam: AnyJSON
        let commentParam: AnyJSON
        switch target {
        case .post(let postId):
            postParam = .string(postId.uuidString)
            commentParam = .null
        case .comment(let commentId):
            postParam = .null
            commentParam = .string(commentId.uuidString)
        }

        let params: [String: AnyJSON] = [
            "p_target_post_id":    postParam,
            "p_target_comment_id": commentParam,
            "p_reason":            .string(trimmed)
        ]

        do {
            // file_appeal returns the uuid of the created appeal (039). Used to start the AI secondary review
            let appealId: String = try await client.rpc("file_appeal", params: params).execute().value
            print("📝 Appeal filed for \(target)")

            // Start the AI secondary review (review-appeal Edge Function, 2026-07-29) fire-and-forget.
            // If it is a clear misjudgment, it is automatically approved within a few seconds to a dozen or so
            // seconds → the 039 trigger restores the post + sends the notification.
            // Even if it fails, the appeal just stays pending in the operator queue, so we do not wait for the result
            Task.detached {
                struct ReviewParams: Encodable { let appealId: String }
                do {
                    try await SupabaseManager.shared.client.functions.invoke(
                        "review-appeal",
                        options: .init(body: ReviewParams(appealId: appealId))
                    )
                    print("🤖 AI appeal review triggered (\(appealId))")
                } catch {
                    print("⚠️ AI appeal review trigger failed (pendingのまま運営キューへ): \(error)")
                }
            }
            return .filed
        } catch {
            // For an existing appeal, file_appeal catches the unique_violation of user_appeals_unique_post/comment
            // and re-raises with RAISE EXCEPTION 'already appealed' (see 039 SQL).
            // We check whether PostgrestError.message contains that text (text matching instead of SQLSTATE, because
            // RAISE EXCEPTION has only a custom message and the SQLSTATE is the generic P0001)
            if let pgError = error as? PostgrestError, pgError.message.contains("already appealed") {
                print("ℹ️ Appeal already filed for \(target)")
                return .alreadyFiled
            }
            print("⚠️ fileAppeal failed for \(target): \(error)")
            return .failed
        }
    }
}
