-- ============================================================
-- Phase A-3: full rewrite of RLS policies + new RPCs
-- ============================================================
-- Purpose:
--   1. Delete the old RPCs (vulnerable versions with no authorization checks at all)
--   2. Tighten RLS on all tables (completely block anon attacks)
--   3. Implement new toggle-style RPCs (trans + auth.uid() + idempotent)
--
-- Tables covered by this file:
--   users / authors / quotes / user_likes / user_follows
--   (user_posts / user_reports / user_blocks / block_sessions get RLS set in each
--    Phase B file at the same time as their own CREATE TABLE)
--
-- Run order:
--   after 001 + 002 are done → this file → Phase B
-- ============================================================

-- ============================================
-- 1. Delete old RPCs (critical: vulnerable versions with no authorization checks at all)
-- ============================================
DROP FUNCTION IF EXISTS public.increment_like_count(uuid);
DROP FUNCTION IF EXISTS public.decrement_like_count(uuid);

-- ============================================
-- 2. Delete all existing policies (covers both old and new names for idempotency)
-- ============================================
-- Old names (before renaming, or auto-generated by Supabase)
DROP POLICY IF EXISTS "authors_select"     ON public.authors;
DROP POLICY IF EXISTS "quotes_select"      ON public.quotes;
DROP POLICY IF EXISTS "user_likes_select"  ON public.user_likes;
DROP POLICY IF EXISTS "user_likes_insert"  ON public.user_likes;
DROP POLICY IF EXISTS "user_likes_delete"  ON public.user_likes;
DROP POLICY IF EXISTS "user_follows_select" ON public.user_follows;
DROP POLICY IF EXISTS "user_follows_insert" ON public.user_follows;
DROP POLICY IF EXISTS "user_follows_delete" ON public.user_follows;

-- New names (the names this file creates, dropped in case of a re-run)
DROP POLICY IF EXISTS "users_select_all"        ON public.users;
DROP POLICY IF EXISTS "users_update_own"        ON public.users;
DROP POLICY IF EXISTS "users_delete_own"        ON public.users;
DROP POLICY IF EXISTS "authors_select_all"      ON public.authors;
DROP POLICY IF EXISTS "quotes_select_all"       ON public.quotes;
DROP POLICY IF EXISTS "user_likes_select_all"   ON public.user_likes;
DROP POLICY IF EXISTS "user_follows_select_all" ON public.user_follows;
DROP POLICY IF EXISTS "user_follows_insert_own" ON public.user_follows;
DROP POLICY IF EXISTS "user_follows_delete_own" ON public.user_follows;

-- ============================================
-- 3. Enable RLS (existing tables are already ON, just in case)
-- ============================================
ALTER TABLE public.users        ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.authors      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.quotes       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_likes   ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_follows ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 4. users table RLS
-- ============================================
-- SELECT: everyone (profiles are public, same as TikTok/Twitter)
CREATE POLICY "users_select_all"
    ON public.users FOR SELECT
    USING (true);

-- INSERT: not allowed directly from clients (only through the trigger)
-- (the handle_new_user trigger inserts with SECURITY DEFINER, so
--  it can bypass RLS, and clients cannot INSERT)

-- UPDATE: own row only (for editing display_name / avatar_url)
CREATE POLICY "users_update_own"
    ON public.users FOR UPDATE
    USING (auth.uid() = id)
    WITH CHECK (auth.uid() = id);

-- DELETE: own row only (account deletion)
CREATE POLICY "users_delete_own"
    ON public.users FOR DELETE
    USING (auth.uid() = id);

-- ============================================
-- 5. authors table RLS (official content)
-- ============================================
-- SELECT: everyone
CREATE POLICY "authors_select_all"
    ON public.authors FOR SELECT
    USING (true);

-- INSERT/UPDATE/DELETE: not allowed for anon/authenticated
-- → only service_role (through the Dashboard) can modify (bypasses RLS)
-- No explicit policy means DENY

-- ============================================
-- 6. quotes table RLS (official quotes)
-- ============================================
CREATE POLICY "quotes_select_all"
    ON public.quotes FOR SELECT
    USING (true);

-- INSERT/UPDATE/DELETE only by service_role (no explicit policy = DENY)

-- ============================================
-- 7. user_likes table RLS
-- ============================================
-- SELECT: everyone (like counts, list of your own likes)
CREATE POLICY "user_likes_select_all"
    ON public.user_likes FOR SELECT
    USING (true);

-- INSERT/UPDATE/DELETE: not allowed directly from clients
-- → only through the toggle_quote_like / toggle_post_like RPCs
-- (the RPCs operate with SECURITY DEFINER, so they bypass RLS)

-- ============================================
-- 8. user_follows table RLS
-- ============================================
-- SELECT: everyone (follower counts)
CREATE POLICY "user_follows_select_all"
    ON public.user_follows FOR SELECT
    USING (true);

-- INSERT: only with your own follower_id
CREATE POLICY "user_follows_insert_own"
    ON public.user_follows FOR INSERT
    WITH CHECK (auth.uid() = follower_id);

-- DELETE: only with your own follower_id
CREATE POLICY "user_follows_delete_own"
    ON public.user_follows FOR DELETE
    USING (auth.uid() = follower_id);

-- UPDATE: not allowed (follow relations are never changed, only added/deleted)

-- ============================================
-- 9. New RPC: official quote toggle_quote_like
-- ============================================
-- Root fix for critical issues 1 and 3:
--   - authentication required via auth.uid()
--   - user_likes change and quotes.like_count update in 1 transaction
--   - idempotent: if already liked, unlike; if not liked, add
CREATE OR REPLACE FUNCTION public.toggle_quote_like(target_quote_id uuid)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    current_user_id  uuid := auth.uid();
    existing_like_id uuid;
    new_count        integer;
    result_is_liked  boolean;
BEGIN
    IF current_user_id IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM public.quotes WHERE id = target_quote_id) THEN
        RAISE EXCEPTION 'Quote not found: %', target_quote_id;
    END IF;

    SELECT id INTO existing_like_id
    FROM public.user_likes
    WHERE user_id = current_user_id AND quote_id = target_quote_id;

    IF existing_like_id IS NOT NULL THEN
        DELETE FROM public.user_likes WHERE id = existing_like_id;
        UPDATE public.quotes
            SET like_count = GREATEST(like_count - 1, 0)
            WHERE id = target_quote_id
            RETURNING like_count INTO new_count;
        result_is_liked := false;
    ELSE
        INSERT INTO public.user_likes (user_id, quote_id)
            VALUES (current_user_id, target_quote_id);
        UPDATE public.quotes
            SET like_count = like_count + 1
            WHERE id = target_quote_id
            RETURNING like_count INTO new_count;
        result_is_liked := true;
    END IF;

    RETURN jsonb_build_object(
        'is_liked',   result_is_liked,
        'like_count', new_count
    );
END;
$$;

-- ============================================
-- 10. Narrow down execute permissions
-- ============================================
-- Make it impossible to call from anon (not logged in)
REVOKE EXECUTE ON FUNCTION public.toggle_quote_like(uuid) FROM anon;
GRANT  EXECUTE ON FUNCTION public.toggle_quote_like(uuid) TO authenticated;

-- Note: toggle_post_like is implemented after the user_posts table is created (file 005)
