-- 064_fix_feed_rpc_grants.sql
--
-- 🔴 Fix for a shipping blocker (found in the 2026-07-31 pre-ship security diff check)
--
-- [What was happening]
-- 063 DROPs fetch_mixed_feed_random(integer) and recreates it with the new signature
-- fetch_mixed_feed_random(integer, text) (063:32-34).
-- But the REVOKE/GRANT at the end was missing.
--
-- PostgreSQL implicitly grants EXECUTE to PUBLIC on CREATE FUNCTION
-- (the same note is in 015_security_audit.sql:136), so after 063 was applied this function was
-- **executable by unauthenticated users (anon)**.
--
-- [Impact]
-- With only the publishable key that can be extracted from the app binary, without logging in,
-- anyone could call
--   POST /rest/v1/rpc/fetch_mixed_feed_random
-- and scrape every post from the last 30 days (body/title/image_path/author_id/display_name/
-- avatar_url) by changing the seed.
-- Also, under SECURITY DEFINER auth.uid() is NULL, so the block exclusion subquery at 063:154-158
-- became an empty set and NOT IN was always true =
-- **all rows were returned with the block feature itself disabled**.
-- In addition, this function is a full scan that computes md5() for every row, and the 046/047 rate
-- limits do not apply, so an unauthenticated user could also consume DB CPU without limit.
--
-- [Preventing recurrence]
-- 029:41 clearly says "a DROP also removes the existing GRANT/REVOKE, so set them again at the
-- end", yet 063 missed it. From now on, whenever you write DROP FUNCTION, always write REVOKE/GRANT
-- as a set at the end of the same file.
-- 052/054/057/062 are CREATE OR REPLACE only (no DROP), so their permissions were kept and
-- they are not affected. 058/059 do DROP, but both reset REVOKE/GRANT correctly.
-- Checking 052 to 063 across the board, the only one missing permissions is this one in 063.

-- ---------------------------------------------------------------------------
-- The fix itself
-- ---------------------------------------------------------------------------
REVOKE EXECUTE ON FUNCTION public.fetch_mixed_feed_random(integer, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.fetch_mixed_feed_random(integer, text) FROM anon;
GRANT  EXECUTE ON FUNCTION public.fetch_mixed_feed_random(integer, text) TO authenticated;

-- ---------------------------------------------------------------------------
-- Verification: run this after applying, and confirm that proacl has no anon= and does have
-- authenticated=X. Also compare whether the other feed RPCs are in the same state.
-- ---------------------------------------------------------------------------
-- SELECT p.proname,
--        pg_get_function_identity_arguments(p.oid) AS args,
--        p.proacl
-- FROM pg_proc p
-- JOIN pg_namespace n ON n.oid = p.pronamespace
-- WHERE n.nspname = 'public'
--   AND p.proname IN ('fetch_mixed_feed_random',
--                     'fetch_following_feed',
--                     'fetch_tag_feed')
-- ORDER BY p.proname;
