-- ============================================================================
-- 074: add a pass condition for "aesthetic/emotional quote images" to the layer 2 ethos rubric
--
-- Background (measured 2026-08-01):
--   The user made 4 test posts, and a monochrome photo of Eminem (image only, no text) came in
--   under confidence 0.8 on Haiku and was escalated to Sonnet. Sonnet's analysis was
--   "treat it as a photo quote of a role model/artist; it is not a study or workout scene, but it
--    does not match any fail category either, so pass as a borderline case" = it only landed there
--   by elimination.
--
--   The cause is the structure of the rubric. Core principle 1 starts with "first identify what scene
--   it is", but motivation images such as night views, monochrome photos or images with typography
--   overlaid are "not any scene". So scene identification fails, and it can only land on the
--   elimination rule at the end, "borderline cases always pass".
--   Elimination is the pattern that small models (Haiku) struggle with the most, and escalation =
--   higher cost + a risk of wobbling toward fail before it reaches Sonnet.
--
--   Also, by structure, atmosphere images without text have no rescue path. The pass condition for
--   "fiction/quoted material" in 057/067 states "if there is no text, follow scene identification as
--   before", so for images without text only elimination is left. The title in the post editor is
--   optional (String? in the InsertRow of UserPostService), so posts without text happen normally by
--   spec. In fact, all 4 test posts that day were "(image only)".
--
-- What this does: create one positive slot on the pass side.
--   The user's intent (stated 2026-08-01): wants "aesthetic / photogenic / emotional / cool" images to
--   pass.
--
-- 🔴 Most important safeguard (a line the user explicitly checked and agreed to):
--   Things listed in the fail categories (junk food, drinking parties, parties, gambling,
--   games, drives etc.) stay fail "with no exceptions at all", however beautifully they are shot or
--   edited. Aesthetic editing is not a reason to rescue a fail category.
--   Without this safeguard it becomes a loophole where "anything passes if you shoot it to look
--   cool", and the fail categories would in effect stop working.
--
-- Method: based on the full ethos_rubric text of 067, insert at only 2 places (same way as 057→067).
--   ⚠️ The text was generated by extracting it mechanically from the 067 file. It was not copied by
--      hand (a copying mistake in a prompt of over 60 lines would become the production judging
--      criteria as is).
--   Insert ①: right after core principle 3: 3 lines that accept the identification result
--      "場面認定なし (雰囲気画像)" ("no scene identified (atmosphere image)")
--   Insert ②: at the end of the pass list: 11 lines for aesthetic/emotional quote images (with the
--      safeguard)
--   All other text (each fail item, the other pass items, the rules for the reason text shown to the
--   user) is not changed by even one character from 067.
--
-- ⚠️ No need to redeploy the Edge Function. moderate-post reads moderation_config every time
--    (same design as 047, which made the model switchable with a single SQL statement).
-- ============================================================================

UPDATE public.moderation_config
SET ethos_rubric = $ethos$
【層2: 「1%」エトス・ルーブリック】
このアプリ「1%」は自己改善・自己抑制をテーマにしたコミュニティです。投稿画像・テキストが
アプリの世界観(勉強・筋トレ・作業・自己改善)に沿っているかを判定してください。

⚠️ 層1優先の原則: 層1(安全性)で fail と判定される内容は、層2(このエトス判定)の
結果に関わらず fail の扱いになります。層2の判定はあくまで層1をクリアした内容に
対してのみ意味を持ちます。自傷・摂食障害・危険行為等、層1に該当しうる内容を
「勉強・筋トレ・自己改善の文脈だから」という理由だけで pass 側に倒さないでください。

判定の大原則 (この順で判定する):
1. まず画像だけを見て「これは何をしている場面か」を一言で認定し、analysis に書いてください
   (例: ドライブ中の車内写真 / ジムでの自撮り / 食事の写真 / 勉強机の写真)。
   認定した場面が下の fail カテゴリに該当するなら、テキストが無くても・行き先や目的が
   書かれていなくても fail とします。「目的が読み取れない」「単なる移動かもしれない」を
   pass の理由にしないでください。
2. 場面認定の際、その画像が「本人・現実の記録 (自撮り、日常の実写、スクリーンショット等)」か
   「映画・アニメ・ドラマ等のフィクション/引用素材 (作品のワンシーン、シネマティックな
   画質・構図、ポスター、有名人の写真)」かも認定し、analysis に書いてください。
3. テキストは場面認定を補強・確定する材料です。画像だけでは中立・境界的でも、テキストが
   娯楽・遊びの文脈を確定させる場合 (例: 「ドライブ」「パチンコで12万勝った」) は
   テキストを優先して fail とします。
   なお「何をしている場面でもない」画像 (夜景・空・抽象アート等、雰囲気や美意識そのものが
   主眼のもの) は、無理に場面をこじつけず「場面認定なし (雰囲気画像)」と認定してください。
   場面が認定できないこと自体は fail の理由になりません。

弾く対象 (fail):
- 明らかなジャンクフード・お菓子 (スナック菓子、菓子パン、ファストフード等) の写真
- スポーツ以外のエンタメを視聴している様子 (ドラマ・お笑い番組・バラエティ・YouTube動画・
  映画を視聴中の画面や様子など)。ただしアイドル・アーティスト本人が写るステージ写真・
  ライブ写真・宣材写真の引用は「視聴している様子」ではなく、ロールモデル引用 (下記 pass)
  として扱う
- 遊んでいる姿 (ゲームをプレイしている様子、遊興・娯楽に興じている様子)
- 遊び・レジャーのお出かけ: ドライブ、男女グループやカップルでの遊び・デートの様子、
  飲み会・パーティー・カラオケ等。車内で複数人が楽しんでいる写真は、行き先のテキストが
  無くてもドライブ/お出かけの場面と認定する。
  ただし一緒に勉強・筋トレ・作業・スポーツをしている様子であれば、人数や性別の構成に
  関わらず pass とする (ジムに男女2人で写っている等は pass)
- ギャンブル: パチンコ・スロット・競馬・カジノ等をしている様子、および勝敗・収支の報告
- ⚠️ 上記の fail カテゴリが「本人・現実の記録」である場合、テキストが名言・決意表明・
  意識の高い文言であっても救済しません (行為の記録はテキストで pass にならない)

許可する対象 (pass):
- パスタ等の食事の写真 (境界的なもの含む。迷ったら許可する)
- スポーツ全般 (格闘技を含む) の実施・観戦
- 映画のポスターや俳優の写真等、モチベーション目的の引用・言及 (視聴中の様子ではなく
  静止画やポスター、名言の引用等)
- フィクション/引用素材のワンシーン画像 (カジノ・豪遊・喧嘩などのシーンを含む) を、
  規律・向上・名言・モチベーションの文脈のテキストと共に投稿するもの。
  画像がフィクション/引用であることが見た目から明らかで、本人が行為をしている記録では
  ないことが条件。テキストが娯楽そのものの賛美 (「カジノ行きたい」「ギャンブル最高」等)
  の場合はこの救済を適用せず fail とする。テキストが無い場合は従来どおり場面認定に従う
- 憧れのロールモデルの引用: 他人のアスリート・モデル・アイドル (K-POPアイドル等) の
  写真の引用投稿。ステージ上のパフォーマンス写真・ライブ写真・宣材写真を含む
  (エンタメを視聴している様子とは区別する。露出やステージ衣装だけを理由に fail にしない)
- 勉強・筋トレ・作業・自己改善に関する内容全般
- フィットネス系の自撮り・進捗報告: ジムでの自撮り、体づくりの進捗、スポーツウェア姿。
  露出があることだけを理由に fail にしない (性的アピールが主目的かどうかは層1で判定する)
- 美的・情緒的な引用画像 (いわゆる「エモい」「aesthetic」「映える」「かっこいい」画像):
  夜景・街並み・空・自然・モノクロ写真・シネマティックな風景・抽象的なアートワーク・
  タイポグラフィを重ねたモチベーション画像など、特定の「行為の場面」が写っておらず、
  雰囲気や美意識そのものを主眼とした画像。人物が写っていなくてもよい。テキストが無くてもよい。
  これらは「何かをしている場面」ではないため、fail カテゴリのいずれにも該当しないものとして
  pass とします。場面が認定できないことを fail の理由にしないでください。
  ⚠️ この救済の条件は「fail カテゴリの場面が写っていないこと」です。画像の中に
  ジャンクフード・ゲーム画面・飲み会・パーティー・ギャンブル・ドライブ等が写っている場合は、
  それがどれだけ美しく撮られていても・加工されていても例外なく fail とします
  (「おしゃれに撮られたジャンクフード」「シネマティックなパチンコ店」「加工した酒の写真」は
  一切救済しない)。美的な加工は fail カテゴリの救済理由になりません

方針: シーン認定が fail カテゴリに明確に該当する場合はテキストの有無に関わらず fail
(フィクション/引用素材・ロールモデル引用の pass 条件を満たす場合を除く)、どのカテゴリにも
明確に該当しない境界例は必ず pass (許可) にしてください。
false negative (本来弾くべきものを見逃す) より false positive (許可すべきものを誤って弾く)
の方がユーザー体験を大きく損ないます。

【本人向け理由文のルール】(層1・層2共通 / safety_reason・ethos_reason の書き方)
- safety_reason / ethos_reason は投稿者本人の画面にそのまま表示される文章です。
  分析・検討の過程は必ず analysis フィールドに書き、reason には結論の説明だけを書いてください。
- 日本語の丁寧語で、2文以内に収めてください。
- 内部用語・判定プロセスに言及しないでください:
  「層1」「層2」「エトス」「1%エトス」「shadow判定」「シャドー判定」「ethos_enforce」
  「confidence」「fail」「pass」「ルーブリック」等の語は reason に書いてはいけません。
- pass の場合の reason は空文字で構いません。
- fail の場合は「投稿のどの部分が」「どの基準に沿わないか」を本人が読んで分かる言葉で
  簡潔に伝えてください。
  例: 「ゲームをプレイしている様子の投稿は、このアプリのテーマ (勉強・運動・自己改善) に
  合わないため表示が制限されました」
$ethos$
WHERE id = true;

-- ============================================================================
-- Check queries (run these after applying and check the results)
-- ============================================================================

-- (A) Whether the 2 inserts are in. Normal if all 3 are true
SELECT ethos_rubric LIKE '%場面認定なし (雰囲気画像)%'          AS 挿入1_雰囲気画像の認定,
       ethos_rubric LIKE '%美的・情緒的な引用画像%'              AS 挿入2_pass条件,
       ethos_rubric LIKE '%美的な加工は fail カテゴリの救済理由になりません%' AS 歯止めの一文
FROM public.moderation_config;

-- (B) Whether the existing conditions of 067 are still there (if all are true, the content of 067 is
-- intact)
SELECT ethos_rubric LIKE '%層1優先の原則%'                       AS 層1優先,
       ethos_rubric LIKE '%憧れのロールモデルの引用%'              AS ロールモデル引用,
       ethos_rubric LIKE '%明らかなジャンクフード%'                AS fail_ジャンクフード,
       ethos_rubric LIKE '%ギャンブル: パチンコ%'                  AS fail_ギャンブル,
       ethos_rubric LIKE '%遊び・レジャーのお出かけ%'              AS fail_レジャー,
       ethos_rubric LIKE '%境界例は必ず pass%'                     AS 境界例はpass
FROM public.moderation_config;

-- (C) Check the effect after applying (after running it for a few days)
--     If the escalation rate went down, it works as intended. If it went up, revise the text
-- SELECT count(*) FILTER (WHERE moderation_verdict ->> 'escalated' = 'true') AS rechecked_by_sonnet,
--        count(*)                                                            AS total_verdicts,
--        round(100.0 * count(*) FILTER (WHERE moderation_verdict ->> 'escalated' = 'true')
--              / NULLIF(count(*), 0), 1)                                     AS escalation_rate
-- FROM public.user_posts WHERE moderation_verdict IS NOT NULL;
